### ISSUE TITLE
(re)use text freely?

### ISSUE THREAD

**Issue by neptunus0001** [davidbgk/open-source-template#7]
Can everything in this repo be used freely? As far as I can judge nothing is said about this. I would like to (re)use text for my project. Can I do that freely?

**Comment by davidbgk** [comment]
Ironically, I didn't set a license to that repository… it's now fixed! Thanks for reporting the issue and feel free to reuse it 🤗

**Comment by neptunus0001** [comment]
Thanks you, I will at least make a reference from my project to this repo.
